stages:
  prepare:
    cmd: uv run python -m src.data.prepare_dataset
    deps:
      - data/raw/UCI_Credit_Card.csv
      - src/data/prepare_dataset.py
      - src/data/clean_dataset.py
      - src/data/validation.py
    outs:
      - data/processed